### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by walduino** [jesseward/jellyfin-plugin-lastfm#1]
Im not at all familiar with .net, visual studio, mono, ....
Any chance you could document the build process on linux ?

With my minimal knowledge and some googling i came to 
`waldo@vm-nas-p2p:~/jellyfin-plugin-lastfm$ xbuild Jellyfin.Plugin.Lastfm.sln
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 28/02/2019 11:23:45.
__________________________________________________
/home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm.sln:  warning : /home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm/Jellyfin.Plugin.Lastfm.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
/home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.
Project "/home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug|Any CPU".
        Target Build:
/home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm/Jellyfin.Plugin.Lastfm.csproj: error : /home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm/Jellyfin.Plugin.Lastfm.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm.sln".-- FAILED
Done building project "/home/waldo/jellyfin-plugin-lastfm/Jellyfin.Plugin.Lastfm.sln".-- FAILED

Build FAILED.`

**Comment by jesseward** [comment]
Hey @walduino thanks for checking in.

I have added build notes to the README. See details in https://github.com/jesseward/jellyfin-plugin-lastfm/commit/df2dc25a83872ad432b532dac351e4eb1d98b518 . Let me know if that works for you. 

Thanks for reporting.

**Comment by walduino** [comment]
Thanks, well documented for a noob like me ! Works
