### ISSUE TITLE
Can't select user to configure for

### ISSUE THREAD

**Issue by Deanosim** [jesseward/jellyfin-plugin-lastfm#16]
When I try to configure the plugin it doesn't let me select a user to configure it for, I've tried deleting the old config, I've tried reinstalling the plugin, but nothing works anymore.

![screenshot](https://user-images.githubusercontent.com/4834976/71643634-f76b6480-2cb3-11ea-859d-e681cb075cfc.png)

**Comment by totoclectic** [comment]
Same here

**Comment by dannymichel** [comment]
Anybody have any luck with this?

**Comment by jesseward** [comment]
apologies for the long delay, I am once again running Jellyfin locally. I believe i have a fix for this will post an update this weekend.

**Comment by jesseward** [comment]
@Deanosim @totoclectic 

I have published release 4.0.0 (https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/4.0.0), please try that and confirm that you're able to scrobble and select the target user.

**Comment by Deanosim** [comment]
Can confirm that 4.0.0 has fixed both problems, I can select/target users and once they are logged in they can scrobble music. Thanks so much for fixing this :)
