### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by dannymichel** [jesseward/jellyfin-plugin-lastfm#17]
Will you be updating this as needed?

**Comment by r0bbie** [comment]
Really missing being able to scrobble from Jellyfin, fingers crossed this plugin hasn't been abandoned (And huge thanks to @jesseward for maintaining it!)

**Comment by jesseward** [comment]
hey, apologies for the delay. I am running Jellyfin locally again. I believe the change for selecting users is minimal and am testing locally. 

I will post an update this weekend. Keep an eye on https://github.com/jesseward/jellyfin-plugin-lastfm/issues/16

**Comment by jesseward** [comment]
Drafted a new release for 10.5.x series controller. See https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/4.0.0
