### ISSUE TITLE
Plugin repository for jellyfin-plugin-lastfm

### ISSUE THREAD

**Issue by jesseward** [jesseward/jellyfin-plugin-lastfm#22]
Evaluate the possibility of creating a 3rd party plugin repo for jellyfin-plugin-lastfm

See: https://jellyfin.org/posts/plugin-updates/

**Comment by Protektor-Desura** [comment]
I did this for my plugin. It only takes about 10-20 minutes to setup and can even be run from here on GitHub. If you have questions let me know.

**Comment by jesseward** [comment]
hey @Protektor-Desura , thanks. I have read through the documentation and have created some automation around the creation of the manifest file (https://github.com/jesseward/jellyfin-utilities/tree/master/manifest-generator) and publishing builds (commit still pending to this repo.).

I still need to test the repo integration with Jellfin itself ;-) though once verified, I will commit the github-action workflow to publish builds and update the manifest

**Comment by jesseward** [comment]
Work for plugin repo has been completed. 

Repo name: LastFM Stable
Repo URL: https://jellyfin.jesseward.com/manifest.json

Details of the automation for the flow can be found in commit:https://github.com/jesseward/jellyfin-plugin-lastfm/commit/868102a036378908d4c28bd2033e1f4452d46b64

**Comment by KristupasSavickas** [comment]
Thanks for all the work!
