### ISSUE TITLE
Add loved tracks import/synchronize

### ISSUE THREAD

**Issue by OdinGitDat** [jesseward/jellyfin-plugin-lastfm#23]
I already have over 2000 loved songs in my lastfm account, it would be nice if this plugin could import those and apply favorite status in the jellyfin library with some clever matching ;)

**Comment by jesseward** [comment]
hey @OdinGitDat , there is logic to do just that (starting at: https://github.com/jesseward/jellyfin-plugin-lastfm/blob/master/Jellyfin.Plugin.Lastfm/ScheduledTasks/ImportLastfmData.cs#L103) , though it may not be working correctly.

I will add this as a TODO and see where things are at.

**Comment by jesseward** [comment]
hey @OdinGitDat , this should now be addressed within commit:https://github.com/jesseward/jellyfin-plugin-lastfm/commit/294ce1a86239a474e3079f2ae903e86b25205b3e and plugin-release [6.0.0.0](https://github.com/jesseward/jellyfin-plugin-lastfm/releases/tag/6.0.0.0) .

It exposes a scheduled task that you can enable for each user that has their LastFM account enabled.

**Comment by OdinGitDat** [comment]
nice! thanks

**Comment by OdinGitDat** [comment]
This is just nitpicky, but it would be nice to get a list of the tracks that were not able to match (in the log or somewhere else).


```
[04:39:00] [INF] [21] Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Retrieved 2584 lovedTracks from LastFM for user Odinoss,
[04:38:42] [INF] [26] Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Syncing LastFM favourties for Odin,
[06:37:37] [INF] [21] Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Finished Last.fm lovedTracks sync for Odin. Matched Songs: 1932
```

I'm saying this because I know for a fact that all my lovedtracks are present in my library, but it was unable to match ~600 of them.  Would be easier to debug the title matching if there was a list of unmatched titles.
