### ISSUE TITLE
Unable to install plugin from repo

### ISSUE THREAD

**Issue by NovaCyntax** [jesseward/jellyfin-plugin-lastfm#26]
When adding repository to Jellyfin using the information provided in README, Jellyfin does not locate the plugin for usage. The following is a screenshot of the repository URL when followed.

![image](https://user-images.githubusercontent.com/20057705/96823041-7f645b80-13f9-11eb-9065-138a33350277.png)

**Comment by jesseward** [comment]
Thanks for reporting this. My Azure subscription changed, unfortunately.

This can be used in the interim while the old repo is cleaned up https://jellyfin-repo.jesseward.com/manifest.json
