### ISSUE TITLE
10.7.0.0 release readiness

### ISSUE THREAD

**Issue by jesseward** [jesseward/jellyfin-plugin-lastfm#30]
Client/Plugin (API/ABI) Developer Notes for  [RC1](https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc1)

* We have migrated from ServiceStack to ASP.NET. Web API endpoints no longer accept HTTP Form requests; everything must be application/json. NOTE: Plugins that implement endpoints will also have to migrate.
* Plugins must now target net5.0.
* IHttpClient removal: Now inject IHttpClientFactory instead.
* HttpException removal: Now catch HttpResponseException instead.
* Services can be registered to the DI pipeline.

**Comment by jesseward** [comment]
Prep being done in 10.7.0.0 [tree](https://github.com/jesseward/jellyfin-plugin-lastfm/tree/10.7.0.0) (https://github.com/jesseward/jellyfin-plugin-lastfm/commit/150932e6121c02ba9bb3a0ee07bb2a8a1655681a)

**Comment by kellcomnet2** [comment]
I know 10.7 is still in RC but do you know/have rough timeline on when the 10.7 version will be available?

**Comment by jesseward** [comment]
hey @kellcomnet2 : i have pushed plugin version 7.0.0.0 to the Repo. This version supports the 10.7.x RC builds

**Comment by kellcomnet2** [comment]
@jesseward thanks, I’ll update tonight.

**Comment by kellcomnet2** [comment]
@jesseward I have installed it manually since it didn't show up via the manifest and have enabled it for my music library. Thank you.

**Comment by jesseward** [comment]
> @jesseward I have installed it manually since it didn't show up via the manifest and have enabled it for my music library. Thank you.

thanks @kellcomnet2 , note that the Repo URL changed in October timeframe. Ensure you're using

```
    Repo name: LastFM Stable
    Repo URL: https://jellyfin-repo.jesseward.com/manifest.json
```

I had tested a repo based install on 10.7 rc3 (which worked), though didn't attempt an upgrade from an existing version........

**Comment by kellcomnet2** [comment]
@jesseward 
URL is correct
even browsing to it via URL doesn't list V7

[{"guid": "5e7fe7f0-b048-429e-a431-b1a7e69c930d", "name": "LastFM", "description": "Scrobble LastFM plays with Jellyfin", "overview": "A plugin that scrobbles your Jellyfin music to LastFM", "owner": "Jesse Ward", "category": "music", "versions": [{"version": "6.0.0.3", "changelog": "Jellyfin LastFM build v6.0.0.3", "targetAbi": "10.6.0.0", "sourceUrl": "https://github.com/jesseward/jellyfin-plugin-lastfm/releases/download/6.0.0.3/lastfm_6.0.0.3.zip", "checksum": "2e35486f5fdccfb1405c3edb88ce9054", "timestamp": "2020-12-16T15:26:49Z"}, {"version": "6.0.0.2", "changelog": "Jellyfin LastFM build v6.0.0.2", "targetAbi": "10.6.0.0", "sourceUrl": "https://github.com/jesseward/jellyfin-plugin-lastfm/releases/download/6.0.0.2/lastfm_6.0.0.2.zip", "checksum": "5f2d86ed9c4cb87197b6dca7a8805bf9", "timestamp": "2020-11-26T19:06:56Z"}, {"version": "6.0.0.1", "changelog": "Jellyfin LastFM build v6.0.0.1", "targetAbi": "10.6.0.0", "sourceUrl": "https://github.com/jesseward/jellyfin-plugin-lastfm/releases/download/6.0.0.1/lastfm_6.0.0.1.zip", "checksum": "ed83070c1c7287425a3126afe3918e73", "timestamp": "2020-10-22T13:25:25Z"}]}]

**Comment by kellcomnet2** [comment]
@jesseward Deleted my last comment as you found the caching issue. Isn't software development fun :) You can have the best code in the world and deployment always has a hiccup.
