### ISSUE TITLE
3rd-party app not srobbling

### ISSUE THREAD

**Issue by LilMistix** [jesseward/jellyfin-plugin-lastfm#37]
Hello !
When I listen to music on my phone it is displayed on last.fm on I listen to it but once the music is finished the scorbbling is not validated, the music simply disappears from lastfm, which is annoying.

**Comment by v1r0x** [comment]
Same problem for me. Currently scrobbled song is correctly displayed on last.fm (`Scrobbling now`), but as soon as the song is finished and the next one is playing, it disappears from list of scrobbled tracks.

**Comment by Saladaa** [comment]
I'm having the same issue. I tried Jellyfin Mobile (Android) and it works as expected. Using 3rd party clients such as Finamp or Gelli, it does not scrobble. However this is not an issue with the plugin really, see the following client issue threads:
for Finamp: https://github.com/UnicornsOnLSD/finamp/issues/87
For Gelli: https://github.com/dkanada/gelli/issues/143
Relevant comment from Jesseward: https://github.com/jesseward/jellyfin-plugin-lastfm/issues/27#issuecomment-744031810

**Comment by jesseward** [comment]
Closing this as a dupe as https://github.com/jesseward/jellyfin-plugin-lastfm/issues/27#issuecomment-744031810 . That issue includes commentary regarding this problem and has references to the upstream issues that are tracking their status. 

I have also added this problem to the list of known issues https://github.com/jesseward/jellyfin-plugin-lastfm#known-issues
