### ISSUE TITLE
If name of song is single word addon favourites all songs of that name by every artist when syncing with Last.fm.

### ISSUE THREAD

**Issue by hugalafutro** [jesseward/jellyfin-plugin-lastfm#40]
Example: 
I "loved" a track named "Lost" by "Labyrinth" on last.fm previously. Afterwards I discovered this addon, and let it sync my "loved" tracks from Last.fm to Jellyfin.

This results in Jellyfin giving heart to every song named "Lost" regardless of artist, ie (loads more above and below this screen):
![image](https://user-images.githubusercontent.com/30209689/165103540-806bbcd7-2850-45e0-88dd-4dc968e419f5.png)

**Comment by hugalafutro** [comment]
It's not only single words it's strings too, seems like the process doesn't check for artist name properly when syncing? Just noticed a "Soldier of Fortune" by "Deep Purple" heart from Last.fm liked another 2 or 3 songs (covers) of that name by different bands on Jellyfin.

**Comment by jesseward** [comment]
Hey @hugalafutro :wave: , thanks for reporting this. I was able to reproduce this problem.

I have pushed a new build (8.0.0.3) that will improve on the matching and enforces comparison against the MusicBrainz Artist name. The updated plugin can be fetched via the JellyFin repo.
