### ISSUE TITLE
Retrieved 0 lovedTracks s from LastFM for user 

### ISSUE THREAD

**Issue by rmarchant** [jesseward/jellyfin-plugin-lastfm#44]
Hello! When attempting to sync my favorites from LastFM to my local client, the task returns:

```
[16:08:21] [INF] [30] Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Syncing LastFM favourties for <jellyfin-user>
[16:08:22] [INF] [21] Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Retrieved 0 lovedTracks from LastFM for user <lastfm-user>
[16:08:22] [INF] [21] Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: User <jellyfin-user> has no loved tracks in last.fm
```
Scrobbling works, and if I favorite a track on the local client, that gets sync'd to Last.fm.

I'm just unable to sync my existing ~255 loved tracks on last.fm to my local client.

Any tips?

Thanks for this plugin either way!

**Comment by OdinGitDat** [comment]
Same problem:

```
Jellyfin.Plugin.Lastfm.Api.RestApi: Fetching LastFM mobilesession auth for Username="Odinoss"
Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Import Last.fm Loved Tracks"
Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Syncing LastFM favourties for "Odin"
Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: Retrieved 0 lovedTracks from LastFM for user "Odinoss"
Jellyfin.Plugin.Lastfm.ScheduledTasks.ImportLastfmData: User "Odin" has no loved tracks in last.fm
Emby.Server.Implementations.ScheduledTasks.TaskManager: "Import Last.fm Loved Tracks" Completed after 0 minute(s) and 1 seconds
```

**Comment by jesseward** [comment]
thanks @rmarchant and @OdinGitDat this was a regression that was introduced at some point during a JSON serialization migration.

I have a change staged in the linked PR that appears to fix. I will perform some more testing (since there are no unit tests in this repo) before merging/cutting a new release.

**Comment by jesseward** [comment]
Plugin version 8.0.0.3 was pushed that includes fixes for this as well as LastFM loved track synchronization.

The update can be downloaded via the plugin repository.
