### ISSUE TITLE
Not able to scobble when Playing through 3rd Party Apps

### ISSUE THREAD

**Issue by kesharwanishreyansh** [jesseward/jellyfin-plugin-lastfm#55]
I am unable to scrobble to lastfm when using, Symfonium to listen to music. 
Live music shows up as "Scrobbling Now" on LastFm, but as soon as the song ends, it doesn't get saved on Lastfm. 
It saves when I play songs on Jellyfin Official client.

Edit: It saves likes even through 3rd Party apps like Symfonium

**Comment by vfedetz** [comment]
I am having this same issue using Jellyfin server with jellyfin-plguin-lastfm installed + the Symfonium mobile Android client app. The scrobbling history is not being saved/tracked in Last.fm.

Currently playing music track shows as "scrobbling now" in last.fm web interface:

![image](https://github.com/jesseward/jellyfin-plugin-lastfm/assets/7075877/10a8e160-562c-4426-bb4b-562e2fd5d04b)

However once track completes, it is not showing in the "recently played tracks" in last.fm or anywhere in last.fm history that I can see:

![image](https://github.com/jesseward/jellyfin-plugin-lastfm/assets/7075877/6492420c-48ef-4cff-a967-3bd0e70f56ee)

**Comment by dpraul** [comment]
Same issue here with Symfonium

**Comment by jesseward** [comment]
hey folks, this is a known issue with the API and the way we're detecting a "played" song. There are some notes in the [README](https://github.com/jesseward/jellyfin-plugin-lastfm?tab=readme-ov-file#3rd-party-jellyfin-applications-gelli-finamp-may-not-scrobble) as well.

At this time, there are no plans to support 3rd party players with this plugin.
