### ISSUE TITLE
Feature request: Top songs in artist page

### ISSUE THREAD

**Issue by mikaelkundert** [jesseward/jellyfin-plugin-lastfm#56]
Currently Airsonic/Subsonic seems to use Last.FM as source of information for displaying top song for any given artist.

I would love to see this plugin providing such functionality. I'm not aware of how Jellyfin is extendable by adding additional lists in artist page, but this would be very valuable feature.

https://www.last.fm/api/show/artist.getTopTracks 

Thanks!

**Comment by mikaelkundert** [comment]
Also, I could consider writing this, but I'm not familiar with dotnet and it's hard to find good documentation how to extend Jellyfin.

**Comment by jesseward** [comment]
hey @mikaelkundert , this is a great idea. Though from what I see, Jellyfin doesn't currently expose the capability to allow customization of the content within the Artist (or Album) pages via a plugin or API call.

This is something you could bring up in their [Matrix/Discord](https://jellyfin.org/contact) channels or raise a post on their [forum](https://forum.jellyfin.org/)

If such functionality was to be built, I suspect the Jellyfin team would create a "provider" for "popular tracks" (or such) for a given artist. That way, it could support a number of providers, for example: Last.FM, Spotify, ... service that exposes an API with popular songs ...
