### ISSUE TITLE
Plugin shows as non supported on Jellyfin 10.9.0

### ISSUE THREAD

**Issue by smittyuk** [jesseward/jellyfin-plugin-lastfm#65]
Hi,

I've ended up upgrading to Jellyfin 10.9.0 and it appears that the plugin is not supported on this version. This is when adding the via the repository - https://jellyfin-repo.jesseward.com/manifest.json.

Does it need an update or is there something wrong on my end?

Thanks

**Comment by jesseward** [comment]
hey @smittyuk , that is interesting. 

would you mind grepping for "lastfm" (grep -i lastfm) in your server logs. I am curious to see if it is tossing any errors.

A few other questions
* Are you trying JF 10.9.0 ? or 10.9.1? 
* Is this a first time install? or upgrading? If upgrading the plugin, try to remove it first and then reinstall.

**Comment by smittyuk** [comment]
Hi,

Thanks for the reponse. This is working now, not sure what changed if anything. This is one 10.9.2, it's scrobbing fine directly from Jellyfin but not from the mobile app Manet I'm aware this is a limitation anyway.

Thanks!

**Comment by smittyuk** [comment]
Resolved
