### ISSUE TITLE
NotSupported? Jellfyin stable 10.9.7

### ISSUE THREAD

**Issue by viasux** [jesseward/jellyfin-plugin-lastfm#68]
![image](https://github.com/jesseward/jellyfin-plugin-lastfm/assets/47131867/bfb201e6-3cca-444f-ae49-11d9105be5a0)

**Comment by pepebarrascout** [comment]
@viasux The last version is 8.1.0.0 but not work in Jellyfin 10.9.x included last version 10.9.7 see https://github.com/jesseward/jellyfin-plugin-lastfm/issues/66

**Comment by viasux** [comment]
closing because its a duplicate
